### ISSUE TITLE
Show "unexpected token" message in inspector

### ISSUE THREAD

**Issue by akoshorvath11** [xeokit/xeokit-bim-viewer#96]
Hi!

I tried the xeokit_bim_viewer and convert2xkt with ProVI IFC out file (IFC4 schema).

``` [IFCOUT2_model.zip](https://github.com/xeokit/xeokit-bim-viewer/files/7302499/IFCOUT2_model.zip)
PS C:\Users\akos.horvath\xeokit\xeokit-convert> node convert2xkt.js -s IFCOUT2_model.ifc -o IFCOUT.xkt -l
[convert2xkt] Reading input file: IFCOUT2_model.ifc
[convert2xkt] Input file size: 76132.93 kB
[convert2xkt] Converting...
unexpected token
Assertion failed: false, at: ./src/wasm/include/web-ifc.h,726,GetSetArgument
Error: RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,726,GetSetArgument). Build with -s ASSERTIONS=1 for more info.
    at abort (C:\Users\akos.horvath\xeokit\xeokit-convert\dist\convert2xkt.cjs.js:6168:19)
    at ___assert_fail (C:\Users\akos.horvath\xeokit\xeokit-convert\dist\convert2xkt.cjs.js:6294:11)
    at <anonymous>:wasm-function[76]:0x464f
    at <anonymous>:wasm-function[952]:0x5490c
    at <anonymous>:wasm-function[986]:0x5ef77
    at <anonymous>:wasm-function[987]:0x5f2b6
    at Object.OpenModel (eval at new_ (C:\Users\akos.horvath\xeokit\xeokit-convert\dist\convert2xkt.cjs.js:9381:31), <anonymous>:8:10)
    at IfcAPI.OpenModel (C:\Users\akos.horvath\xeokit\xeokit-convert\dist\convert2xkt.cjs.js:41863:34)
    at C:\Users\akos.horvath\xeokit\xeokit-convert\dist\convert2xkt.cjs.js:42075:36
```

Thank you in advance for your answer!
[IFCOUT2_model.zip](https://github.com/xeokit/xeokit-bim-viewer/files/7302532/IFCOUT2_model.zip)

**Comment by xeolabs** [comment]
Hi, this issue appears to be related to the web-ifc library, which convert2xkt uses internally to parse the IFC. 

So, it's not something we can fix in xeokit - suggest logging this issue here (although you'll need to somehow reproduce in the context of web-ifc): https://github.com/tomvandig/web-ifc

Are any other IFC files converting OK for you BTW, using convert2xkt?
